### ISSUE TITLE
Duplicate log-XX IDs cause unviewable test results output

### ISSUE THREAD

**Issue by johnsca** [juju-solutions/cwr-status#23]
http://status.juju.solutions/bundle/07dcc1cea8ab4614802b17432c3a43d0

The two failed test cases have useful output that indicates the tests failed due to timeout.  However, this output is not shown when you click on the test item because the IDs used to associate the hidden `<textarea>` with the correct test result output are duplicated and so the output for different tests are shown instead.

For example, the `10-bundles-test.py` result for `cs:trusty/ganglia-2` has `id="log-23"` which is the same as the `01-bundle.py` result for `bundle`.

**Comment by seman** [comment]
Resolved by #25
